apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-setup
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:8.4
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Install wget
          yum update -y && yum install -y wget && yum clean all
          
          # Download the SQL file
          wget -O data.sql https://drive.google.com/uc?export=download&id=1AC2uvs6f2t4qrhXpz5XowSxoVXR3TfvG
          
          
          # Check if the file was downloaded successfully
          if [ ! -f data.sql ]; then
            echo "Failed to download data.sql"
            exit 1
          fi
          
          # Execute SQL commands

          mysql -h kb-mysql -u root -p$MYSQL_ROOT_PASSWORD <<EOF
          CREATE IF NOT EXISTS DATABASE google;
          ALTER USER 'metabase'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
          GRANT ALL PRIVILEGES ON metabase.* TO 'metabase'@'%';
          GRANT ALL PRIVILEGES ON google.* TO 'metabase'@'%';
          FLUSH PRIVILEGES;
          EOF
          
          # Import the SQL file
          mysql -h kb-mysql -u root -p$MYSQL_ROOT_PASSWORD google < data.sql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
      restartPolicy: OnFailure