apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 encoded "rootpassword"
  MYSQL_DATABASE: bWV0YWJhc2U=  # base64 encoded "metabase"
  MYSQL_USER: bWV0YWJhc2U=  # base64 encoded "metabase"
  MYSQL_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"