apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-setup
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:8.0
        command: ["/bin/sh", "-c"]
        args:
        - |
          wget -O data.sql https://drive.google.com/uc?export=download&id=1AC2uvs6f2t4qrhXpz5XowSxoVXR3TfvG
          mysql -h kb-mysql -u root -p$MYSQL_ROOT_PASSWORD <<EOF
          ALTER USER 'metabase'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
          GRANT ALL PRIVILEGES ON metabase.* TO 'metabase'@'%';
          FLUSH PRIVILEGES;
          source data.sql;
          EOF
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
      restartPolicy: OnFailure