apiVersion: batch/v1
kind: Job
metadata:
  name: metabase-setup
spec:
  template:
    spec:
      # initContainers:
      # - name: wait-for-metabase-setup
      #   image: busybox
      #   command: ['sh', '-c', 'until nslookup kb-metabase; do echo waiting for metabase; sleep 2; done']
      containers:
      - name: metabase-setup
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Install curl
          apk add --no-cache curl
        

          # Instalar jq
          apk add --no-cache jq

          # Wait for Metabase to be ready
          until curl -s http://kb-metabase/api/health | grep -q "ok"; do
            echo "Waiting for Metabase to start..."
            sleep 10
          done

          # Get setup token
          SETUP_TOKEN=$(curl -s http://kb-metabase/api/session/properties | jq -r '.["setup-token"]')

          # Set up admin account
          curl -X POST http://kb-metabase/api/setup \
            -H "Content-Type: application/json" \
            -d '{
              "token": "'$SETUP_TOKEN'",
              "user": {
                "first_name": "augusto",
                "last_name": "kark",
                "email": "'$ADMIN_EMAIL'",
                "password": "'$ADMIN_PASSWORD'",
                "password_confirm": "'$ADMIN_PASSWORD'"
              },
              "prefs": {
                "site_name": "UM",
                "site_locale": "en"
              }
            }'

          # Get session token
          SESSION_TOKEN=$(curl -X POST http://kb-metabase/api/session \
            -H "Content-Type: application/json" \
            -d '{
              "username": "'$ADMIN_EMAIL'",
              "password": "'$ADMIN_PASSWORD'"
            }' | jq -r '.id')

          # Add database connection
          DB_ID=$(curl -X POST http://kb-metabase/api/database \
            -H "Content-Type: application/json" \
            -H "X-Metabase-Session: $SESSION_TOKEN" \
            -d '{
              "engine": "mysql",
              "name": "mobility",
              "details": {
                "host": "kb-mysql",
                "port": 3306,
                "dbname": "'$DB_NAME'",
                "user": "'$DB_USER'",
                "password": "'$DB_PASSWORD'"
              },
              "is_full_sync": true,
              "auto_run_queries": true
            }' | jq -r '.id')

          # Get the correct table ID
          TABLE_ID=$(curl -X GET http://kb-metabase/api/database/$DB_ID/tables \
            -H "X-Metabase-Session: $SESSION_TOKEN" \
            | jq -r '.[0].id')

          # Create question using the correct table ID
          QUESTION_ID=$(curl -X POST http://kb-metabase/api/card \
            -H "Content-Type: application/json" \
            -H "X-Metabase-Session: $SESSION_TOKEN" \
            -d '{
              "name": "average mendoza",
              "type": "question",
              "dataset_query": {
                "database": '"$DB_ID"',
                "type": "query",
                "query": {
                  "source-table": '"$TABLE_ID"',
                  "aggregation": [
                    ["avg", ["field", 83, {"base-type": "type/Integer"}]],
                    ["avg", ["field", 81, {"base-type": "type/Integer"}]],
                    ["avg", ["field", 72, {"base-type": "type/Integer"}]],
                    ["avg", ["field", 80, {"base-type": "type/Integer"}]],
                    ["avg", ["field", 78, {"base-type": "type/Integer"}]],
                    ["avg", ["field", 86, {"base-type": "type/Integer"}]]
                  ],
                  "breakout": [["field", 73, {"base-type": "type/DateTime", "temporal-unit": "day"}]],
                  "filter": ["and", ["=", ["field", 85, {"base-type": "type/Text"}], "Mendoza Province"], ["=", ["field", 75, {"base-type": "type/Text"}], "Capital Department"], ["between", ["field", 73, {"base-type": "type/DateTime"}], "2020-01-01", "2020-12-31"]]
                }
              },
              "display": "area",
              "visualization_settings": {
                "stackable.stack_type": null,
                "graph.dimensions": ["date"],
                "graph.metrics": ["avg", "avg_2", "avg_3", "avg_4", "avg_5", "avg_6"]
              }
            }' | jq -r '.id')

          
        env:
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: metabase-secret
              key: ADMIN_EMAIL
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metabase-secret
              key: ADMIN_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
      restartPolicy: OnFailure
